---
title: "Data plot deconstruction"
output: html_document
date: "2024-05-15"
---

```{r}
library(readr)
library(tidyverse)
```

```{r}
library(readr)
DataPlot <- read_csv("DataPlot.csv")
View(DataPlot)
```
```{r}
ggplot(DataPlot, aes(x = count, y = main, fill = group)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ group, scales = "free_y", ncol = 1) + 
  scale_x_log10() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Estimated number of described species",
       x = "Count(Log10)",
       y = "Group") +
  theme_minimal()
```

```{r}
ggplot(DataPlot, aes(x = count, y = main, fill = group)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  geom_text(aes(label = count),nudge_x=-0.3) +
  facet_wrap(~ group, scales = "free_y", ncol = 1) +
  scale_x_log10() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Estimated number of described species",
       x = "Count",
       y = "Group") +
  theme_minimal()
```
```{r}
library(ggplot2)
library(viridis)

ggplot(DataPlot, aes(x = count, y = main, fill = group)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  geom_text(aes(label = count), nudge_x = -0.3, color = "white", size = 3.5) +  
  facet_wrap(~ group, scales = "free_y", ncol = 2, nrow = 2) +  
  scale_x_log10() +
  scale_fill_viridis_d() +  
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
    title = "Estimated Number of Described Species",
    x = "Count ",
    y = "Group"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10)
  )
```





```{r}
species <- read.csv("speciescount.csv")
View(species)
```

```{r}
ggplot(species, aes(x = count, y = reorder(main, count))) +
  geom_bar(stat = "identity", show.legend = FALSE, fill = "royalblue4") +
  geom_text(aes(label = count), hjust = 1.1, color = "white") + # Adjust text position
  scale_x_continuous(trans = "log10", breaks = c(1, 10, 100, 1000, 10000, 100000, 1000000)) + # Log scale
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5),
        plot.title.position = "plot", # Center title
        plot.margin = margin(20, 20, 20, 20, "pt")) + # Adjust margins
  ggtitle("Number of described species") + # Set title
  labs(x = "Count", y = "Group") +
  theme_minimal()


```

















