---
title: "Data plot deconstruction"
output:
  pdf_document: default
  html_document: default
date: "2024-05-15"
---

##Installing/Loading packages
```{r}
library(readr)
library(tidyverse)
```


##Reading table from excel
```{r}
library(readr)
DataPlot <- DataPlot <- read_csv("~/Data analysis JCU/R-module-JCU-/data/DataPlot.csv")
View(DataPlot)
```

##Faceted plot code split according to group
```{r}
ggplot(DataPlot, aes(x = count, y = main, fill = group)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  geom_text(aes(label = count), nudge_x = -0.5, size = 3.2) +  
  facet_wrap(~ group, scales = "free_y", ncol = 2, nrow = 2) +  
  scale_x_log10() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
    x = "Count ",
    y = "Group"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10)
  )
```

##Code for overall count of groups of animals globally 
```{r}
ggplot(DataPlot, aes(x = count, y = reorder(main, count))) +
  geom_bar(stat = "identity", show.legend = FALSE, fill = "royalblue4") +
  geom_text(aes(label = count), hjust = 1.1, color = "white") + # Adjust text position
  scale_x_continuous(trans = "log10", breaks = c(1, 10, 100, 1000, 10000, 100000, 1000000)) + # Log scale
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5),
        plot.title.position = "plot", # Center title
        plot.margin = margin(20, 20, 20, 20, "pt")) + # Adjust margins
  labs(x = "Count", y = "Group") +
  theme_minimal()


```

















